### ISSUE TITLE
How to review the SVG by hotkey?

### ISSUE THREAD

**Issue by arthurwxl** [lishu/vscode-svg2#127]
Hi Team,

I just checked the MD, however, there are no instructions for how to use the hotkey to review, is there a document for showing that? Thanks.

**Comment by lishu** [comment]
This extension doesn't bind any hotkey, because it can be done by user.

The default binding is too easy to conflict with other extensions of the user.

After version `1.4.23`, the Previewer `svg.showSvg` can be [add hotkey](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor), previously, it was a private command.
