### ISSUE TITLE
How can I use the prettifier to delete unecessary attributes

### ISSUE THREAD

**Issue by janstieler** [lishu/vscode-svg2#137]
Hi,
in the command palette I get no displayed a prettify command.
Or I'm wrong with prettify? I used it under Atom with the SVGO Plugin to delete some not necessary attributes in the svg.
SVGMO as example allows also to delete the unnecessary (xmlns:xlink) attributes. 
Is there also a possibility to change color classes to fill?

Cheers

**Comment by lishu** [comment]
Due to SVGO compatibility issues, the earlier prettify commands have been removed and replaced with normal HTML-based formatting.

However, you can adjust all SVG compression options in the settings to get a similar effect through compression, but SVGO has limited support for more complex reference relationships, so please back up the original file before operation.

**Comment by janstieler** [comment]
Thanks,
also if this is not really unsatisfying.
