### ISSUE TITLE
How to config the prefixIds params?

### ISSUE THREAD

**Issue by imjeen** [lishu/vscode-svg2#5]
I want to config the svgo about [prefixIds](https://github.com/svg/svgo/blob/master/plugins/prefixIds.js), like below:

```YAML
// YAML file
- prefixIds
    delim: '_TEST_'
```

but I only got the `"svg.minify.prefixIds": true` in the **.vscode/setting.json**.

**Comment by lishu** [comment]
Sorry this issue cannot be resolved at this time. Due to some network issues, I can't successfully run vscode packaging recently.

You can try modifty 
`%USERPROFILE%\.vscode\extensions\jock.svg-1.0.5\package.json`
Line:247 
Old: 
`"type": "boolean",`
**Change to:**
`"type": ["boolean", "object"],`

Finally, Close All vscode & reopen it.
